### ISSUE TITLE
Error "collector doesn\'t have me2 active" 

### ISSUE THREAD

**Issue by jaime0720** [mercadopago/cart-prestashop-7#2]
Greetings from Mexico!, I have Prestashop 1.7.2.4, with the module Mercado Pago 1.0.14 installed on it, the problem with the module occurs when a product is added to cart, after you fill all the info (name, address, etc) to make the payment, when you press pay button to be redirected to Mercado Pago website redirection does not work, instead the screen becomes white with no more action, and the Prestashop log shows this error: "MercadoPago::exec = collector doesn\'t have me2 active". I have verified and my account of Mercado Pago has Mercado Envios activated and also is activated in the module itself. I am using standard chekout, do you have an idea what could be wrong? Thanks in advance.

**Comment by joelibaceta** [comment]
Hello @jaime0720 is its correct, we are turning off Mercado Envios for new sellers temporally, this feature will be available in the future again, we are working for improve the shipping experience.
